class Students {
static  List imalat = [
    "ESMAGÜL AKPINAR",
    "HANİFE ANDAÇ",
    "MUSTAFA BURAK ARICI",
    "ABDULKADİR ARSLAN",
    "MEHMET ALİ ASMAN",
    "SARE BETÜL AY",
    "HASAN AYDIN",
    "ALİ METEHAN AZINARIĞ",
    "ESRA BAŞPINAR",
    "ERAY ÇAĞTAŞ",
    "EMRE ÇALIŞKAN",
    "SENEM CANPOLAT",
    "RUMEYSA ÇETİNALP",
    "SEDANUR ÇINAR",
   // "ALİ EREN DEMİRELLER",
    "SERKAN DEVECİ",
    "DOĞA DOĞAN",
    "ÖZGÜR DOĞANOĞLU",
    "ABDULKERİM DOĞU",
    "GÖKAY EFE EKŞİ",
    "EMEL ERGÜN",
    "MUSTAFA YİĞİT GÜL",
    "BERKAY GÜLŞEN",
    "BARAN İLGÜN",
    "BERK İŞİKAN",
    "EMRE KALYONCU",
    "SELENDİZ KAPUCU",
    "MUSA KAYA",
    "AHMET HAKAN KILIÇOĞLU",
    "EDA KURNAZ",
    "BERKE ORMANCI",
    "RIDVAN ÖZTÜRK",
    "GÖRKEM ŞABANÇELEBİ",
    "EYÜP ŞAHİN",
    "MERT ŞENER",
    "EFE GÖRKEM SIRYOL",
    "ERAY TOPCU",
    "BEYTULLAH KERİM TÜRKEL",
    "ÖZGÜR ULUÇAY",
    "BEYZA ÜRETEN",
    "ÜMMÜHAN UZUNOĞLU",
    "BARLAS VERGİLİ",
    "FIRAT YALÇIN",
    "ESRA NURCAN YAVUZ",
    "MUHAMMED HARUN YILDIZ",
    "ATAKAN YILMAZ",
    "KAAN YILMAZ",
    "SERHAT YILMAZ"
  ];
static  List sayisalElektronik = [
    "ESMAGÜL",
        "HANİFE",
        "MUSTAFA",
        "MELİSSA",
        "HASAN",
        "EMİRHAN",
        "ALİ",
        "ZEHRA ",
        "ESRA ",
        "ERAY ",
        "EMRE ",
        "KÜRŞATCAN ",
        "SENEM ",
        "RUMEYSA ",
        "SEDANUR ",
        "SERKAN ",
        "DOĞA ",
        "ÖZGÜR ",
        "ABDULKERİM ",
        "EMEL ",
        "MUSTAFA  ",
        "BERKAY ",
        "BARAN ",
        "BERK ",
        "BURAK ",
        "EMRE ",
        "SELENDİZ ",
        "BATUHAN ",
        "MUSA ",
        "SADIK ",
        "AHMET  ",
        "İBRAHİM ",
        "EDA ",
        "BERKE ",
        "RIDVAN ",
        "GÖRKEM ",
        "EYÜP ",
        "MERT ",
        "EFE  ",
        "ERAY ",
        "BEYTULLAH  ",
        "ÖZGÜR ",
        "ALPER ",
        "BEYZA ",
        "BARLAS ",
        "FIRAT ",
        "ESRA  ",
        "MUHAMMED ",
        "ATAKAN ",
        "KAAN "
  ];
 static List bilgisayarGuvenligi = [
    "ESMAGÜL ",
    "HANİFE ",
    "MUSTAFA  ",
    "ABDULKADİR ",
    "MEHMET  ",
    "SARE  ",
    "EMİRHAN  ",
    "ZEHRA ",
    "ESRA ",
    "EMRE ",
    "KÜRŞATCAN ",
    "SENEM ",
    "RUMEYSA ",
    "SEDANUR ",
    "ALİ EREN",
    "SERKAN ",
    "DOĞA ",
    "ÖZGÜR ",
    "ABDULKERİM ",
    "GÖKAY ",
    "EMEL ",
    "BERKAY ",
    "BARAN ",
    "BERK ",
    "BURAK ",
    "EMRE ",
    " SELENDİZ ",
    " BATUHAN ",
    " MUSA ",
    "SADIK ",
    " İBRAHİM ",
    "EDA ",
    "RIDVAN ",
    "GÖRKEM ",
    "EYÜP ",
    " MERT ",
    "EFE  ",
    "ERAY ",
    "ÖZGÜR ",
    "BEYZA ",
    "EDA NUR",
    "BARLAS",
    "FIRAT",
    " ESRA",
    "MUHAMMED",
    "ATAKAN",
    "KAAN",
    "SERHAT"
  ];
 static List selectedSayisal = [""];
static List selectedImalat = [""];
static List selectedGuvenlik = [""];
}